### ISSUE TITLE
Investigate on how could we use the watch functionality

### ISSUE THREAD

**Issue by Rolitoansu** [Arquisoft/wichat_en1b#140]

**Comment by pglez82** [comment]
There is also the option of profiles. Maybe for dev you do not need prometheus and graphana so you can create a profile that excludes this two services.

Removing the dependencies can be problematic because if we launch certain services before having the database running, it can lead to connection errors.

**Comment by Rolitoansu** [comment]
> There is also the option of profiles. Maybe for dev you do not need prometheus and graphana so you can create a profile that excludes this two services.

Okay, I'll take a look into that.

> Removing the dependencies can be problematic because if we launch certain services before having the database running, it can lead to connection errors.

We could leave the mogodb dependency, since it wouldn't be reloaded (we could put `sync` as action so it doesn't reload but synchronizes files, or even leave as is). Other dependencies would still be problematic (between webapp and gateway, and gateway with back-end services, for example).

**Comment by Rolitoansu** [comment]
Okay, instead of using `reload` the action `sync+reload` doesn't generate the errors mentioned before. It reloads the context without affecting other services and doesn't restart until it regenerated the container.

**Comment by orvizz** [comment]
I took a look to the [Docker Compose Watch](https://docs.docker.com/compose/how-tos/file-watch/) documentation.
It seems like the `sync` action it's used when we want to synchronize the contents of the local files we're working on with the contents of the files in their corresponding Docker container. Therefore, `sync` action could be useful to keep the code updated:
```yml
services:
  web:
    build: .
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
```

On the other hand, the action `rebuild` is used to indicate docker that it should generate a new image of the container and replace the previous one with the new image whenever a save action is performed. Assigning the `rebuild` action to all the files in the container could be costly as any minor change will rebuild the container. This could have a low impact when applied to the backend containers as they build quite fast, but in the React webapp it will take a lot of time. This action is intended to act over the `package.json` package, so that the image will only rebuild whenever we change or add new dependencies (`rebuild` is a must in this cases, otherwise the new dependencies will not be installed in the container)

```yml
services:
  web:
    build: .
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
```

Finally, there's another action called `sync+restart`. This action synchronizes the files and restart the container. This action is intended to use over configuration files and with code that does not automatically update themselves.

```yml
services:
  web:
    build: .
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app/web
          ignore:
            - node_modules/
        - action: sync+restart
          path: ./proxy/nginx.conf
          target: /etc/nginx/conf.d/default.conf
```

## Proposal

As the backend modules are not reactive, we could use `sync+restart` over this modules. We need to rerun them when we update the files. In the other hand, for the React module, changes update automatically whenever we make any kind of change in the code as it supports "hot reload".

My suggestion is to use `sync+restart` in the gateway service and the other services, `sync` in the webapp and `rebuild` over all the `package.json` files of the modules.

For the statistics service:

```yml
statisticservice:
    container_name: statisticservice-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/statisticservice:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./statisticservice
    develop:
      watch:
        - action: sync+restart
          path: ./statisticservice
          target: /usr/src/statisticservice
          ignore:
            - node_modules
        - action: rebuild
          path: ./statisticservice/package.json
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
```

And for the webapp:

```yml
webapp:
    container_name: webapp-wichat_en1b
    image: ghcr.io/arquisoft/wichat_en1b/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    develop:
      watch:
        - action: sync
          path: ./webapp
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./webapp/package.json 
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"
```
